name: finance_app
description: A personal finance manager built with Flutter.
publish_to: 'none' # this is a sample project
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
    intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true



flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: uk
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated