// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBudbEvcqWtI2Uwf9YXQ5xQeQDa-GhGjRw',
    appId: '1:175071606634:web:9b3548a56c4fef1f90d713',
    messagingSenderId: '175071606634',
    projectId: 'finmate-bc9a4',
    authDomain: 'finmate-bc9a4.firebaseapp.com',
    storageBucket: 'finmate-bc9a4.firebasestorage.app',
    measurementId: 'G-EG7V123EHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjlyepZ1birckiAd05DqBOtglL_FE1z-U',
    appId: '1:175071606634:android:ca002be25b0ac54a90d713',
    messagingSenderId: '175071606634',
    projectId: 'finmate-bc9a4',
    storageBucket: 'finmate-bc9a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm9cTdtwGX7jtOQJn_HeQD_QrOVgckpV0',
    appId: '1:175071606634:ios:e5a3f3106f99173790d713',
    messagingSenderId: '175071606634',
    projectId: 'finmate-bc9a4',
    storageBucket: 'finmate-bc9a4.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm9cTdtwGX7jtOQJn_HeQD_QrOVgckpV0',
    appId: '1:175071606634:ios:e5a3f3106f99173790d713',
    messagingSenderId: '175071606634',
    projectId: 'finmate-bc9a4',
    storageBucket: 'finmate-bc9a4.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBudbEvcqWtI2Uwf9YXQ5xQeQDa-GhGjRw',
    appId: '1:175071606634:web:58a22c85b235417190d713',
    messagingSenderId: '175071606634',
    projectId: 'finmate-bc9a4',
    authDomain: 'finmate-bc9a4.firebaseapp.com',
    storageBucket: 'finmate-bc9a4.firebasestorage.app',
    measurementId: 'G-G614EMK6RG',
  );
}
